openapi: 3.0.3
info:
  title: 'ms-user'
  description: Пользователи системы
  version: 1.1.0

servers:
  - url: http://{url}/api/
    variables:
      url:
        default: localhost:11555  # AGW
security:
  - bearerAuth: []

tags:
  - name: Public API
    description: Публичное API

paths:
  /user/current:
    get:
      tags:
        - Public API
      operationId: getCurrentUser
      summary: Получение своего пользователя
      responses:
        '200':
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          $ref: '../lib-api-base/base.yml#/components/responses/400Error'
        '500':
          $ref: '../lib-api-base/base.yml#/components/responses/500Error'

  /user/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        description: id пользователя
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Public API
      operationId: getUserById
      summary: Получение пользователя по id
      responses:
        '200':
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          $ref: '../lib-api-base/base.yml#/components/responses/404Error'
        '500':
          $ref: '../lib-api-base/base.yml#/components/responses/500Error'
          
  /user/search:
    parameters:
      - name: first_name
        in: query
        required: true
        description: Условие поиска по имени
        schema:
          type: string
          example: Ива
      - name: last_name
        schema:
          type: string
          description: Часть фамилии для поиска
          example: Ивано
        in: query
        required: true
        description: Условие поиска по фамилии
    get:
      tags:
        - Public API
      operationId: searchUserByNames
      summary: Поиск анкет по фамилии и имени
      responses:
        '200':
          description: Список анкет
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSearchResponse'
        '404':
          $ref: '../lib-api-base/base.yml#/components/responses/404Error'
        '500':
          $ref: '../lib-api-base/base.yml#/components/responses/500Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserResponse:
      type: object
      description: Пользователь
      required:
        - firstName
        - secondName
        - birthdate
        - sex
      properties:
        id:
          type: string
          format: uuid
          description: ID
        firstName:
          type: string
          description: Имя
        secondName:
          type: string
          description: Фамилия
        birthdate:
          type: string
          format: 'date'
          description: Дата рождения
        sex:
          $ref: "../lib-api-base/base.yml#/components/schemas/Sex"
        biography:
          type: string
          description: Хобби, интересы и т.п.
        city:
          type: string
          description: Москва

    UserSearchResponse:
      type: object
      required:
        - totalQnt
        - users
      properties:
        totalQnt:
          type: integer
          format: int64
          description: Количество найденных записей
        users:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/UserResponse'